hydra:
  run:
    dir: outputs/${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job:
    chdir: True
train:
  size: 1800000
  path: /work/gallim/SIMStudies/FlashSimStudies/preprocessing/preprocessed_photons/train.parquet
  batch_size: 2048
test:
  size: 200000
  path: /work/gallim/SIMStudies/FlashSimStudies/preprocessing/preprocessed_photons/test.parquet
  batch_size: 2048
pipe: pipe1_bis
context_variables:
  - GenPho_pt
  - GenPho_eta
  - GenPho_phi
  - GenPho_status
  - ClosestGenJet_pt
  - ClosestGenJet_mass
  - PU_gpudensity
  - PU_nPU
  - PU_nTrueInt
  - PU_pudensity
  - PU_sumEOOT
  - PU_sumLOOT
target_variables:
  - RecoPho_r9
  - RecoPho_sieie
  - RecoPho_energyErr
  - RecoPhoGenPho_ptratio
  - RecoPhoGenPho_deltaeta
  - RecoPho_s4
  - RecoPho_sieip
  - RecoPho_x_calo
  - RecoPho_mvaID
  - RecoPho_eCorr
  - RecoPho_pfRelIso03_all
  - RecoPho_pfRelIso03_chg
  - RecoPho_esEffSigmaRR
  - RecoPho_hoe
model:
  maf:
    num_steps: 20
    num_transform_blocks: 8
    dropout_probability: 0.0
    use_residual_blocks: False
    batch_norm: True
    hidden_dim: 128
    affine_type: sigmoid
  arqs:
    num_steps: 0
    num_transform_blocks: 5
    dropout_probability: 0.1
    use_residual_blocks: True
    batch_norm: True
    hidden_dim: 300
    num_bins: 64
    tail_bound: 5.0
  caf:
    num_steps: 0
    hidden_dim: 64
  activation: relu
  permute_type: random-permutation
  init_identity: True
distributed: False
epochs: 600
sample_every: 5
checkpoint: null
optimizer:
  learning_rate: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-5
stopper:
  patience: 20
  min_delta: 0.005
